### ISSUE TITLE
Links to Cogcomp2 resource are broken

### ISSUE THREAD

**Issue by BobbyL2k** [LIAAD/tieval#16]
The links to Cogcomp2 model & resource are broken.

The location of the links within the repo is linked bellow.
https://github.com/LIAAD/tieval/blob/a633041493f655ebc6b051def7edb754341dbfe3/tieval/models/metadata.py#L4
https://github.com/LIAAD/tieval/blob/a633041493f655ebc6b051def7edb754341dbfe3/tieval/models/metadata.py#L5

**Comment by hmosousa** [comment]
Hi @BobbyL2k 

In fact, the links are broken. I will fix them.

Thank you for creating the issue.
